# Generated by Django 2.1.3 on 2018-11-25 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_auto_20181125_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
