# Generated by Django 2.1.3 on 2018-11-25 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_auto_20181125_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado_pago',
            field=models.CharField(blank=True, choices=[('1', 'PAGO PENDIENTE'), ('2', 'PAGADO'), ('3', 'EN CAMINO'), ('4', 'ENTREGADO')], max_length=100, null=True),
        ),
    ]
