# Generated by Django 2.1.3 on 2018-11-25 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_pedido_estado_pago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='estado_pago',
            new_name='estado_pedido',
        ),
    ]
