# Generated by Django 2.1.3 on 2018-11-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0009_auto_20181127_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('1', 'Sin leer'), ('2', 'Leido')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
