# Generated by Django 2.1.3 on 2018-11-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0011_auto_20181129_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='estado',
            field=models.CharField(choices=[('Sin leer', 'Sin leer'), ('Leido', 'Leido')], max_length=50),
        ),
    ]
