# Generated by Django 2.1.3 on 2018-12-30 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0012_auto_20181129_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id_conekta',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='id_envio',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='id_pago',
        ),
    ]
