# Generated by Django 2.1.3 on 2019-01-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0013_auto_20181230_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto_pedido',
            name='talla',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
