# Generated by Django 2.1.3 on 2019-01-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0014_producto_pedido_talla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
