# Generated by Django 2.1.3 on 2019-01-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0015_auto_20190104_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='usuario',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
