# Generated by Django 2.1.3 on 2019-01-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0016_auto_20190104_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='comprobante',
            field=models.ImageField(blank=True, null=True, upload_to='Comprobantes'),
        ),
    ]
