# Generated by Django 2.1.3 on 2019-01-07 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0018_auto_20190107_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='producto',
            new_name='usuario',
        ),
    ]
