# Generated by Django 2.1.3 on 2019-02-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0022_auto_20190222_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='colonia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
