# Generated by Django 2.1.3 on 2019-02-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0023_pedido_colonia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='direccion',
            new_name='calle',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='calle',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='colonia',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='no_exterior',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='no_interior',
        ),
        migrations.AddField(
            model_name='cliente',
            name='colonia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='no_exterior',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='no_interior',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
