# Generated by Django 2.1.3 on 2019-02-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0024_auto_20190222_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='numero_guia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='servicio_mensajeria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
