# Generated by Django 2.1.3 on 2018-11-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_auto_20181111_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
