# Generated by Django 2.1.3 on 2018-12-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_auto_20181228_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tallas',
            field=models.ManyToManyField(blank=True, to='ecommerce.Talla'),
        ),
    ]
