# Generated by Django 2.1.3 on 2019-02-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_auto_20190112_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='en_tienda',
            field=models.BooleanField(default=True),
        ),
    ]
