# Generated by Django 2.1.3 on 2018-11-06 04:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrusel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(blank=True, max_length=100)),
                ('imagen', models.ImageField(upload_to='Carrusel')),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Carrusel',
                'verbose_name_plural': 'Carruseles',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('mision', ckeditor.fields.RichTextField()),
                ('vision', ckeditor.fields.RichTextField()),
                ('valores', ckeditor.fields.RichTextField()),
                ('historia', ckeditor.fields.RichTextField()),
                ('giro_de_la_empresa', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=200)),
                ('respuesta', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Marcas')),
            ],
        ),
    ]
