# Generated by Django 2.1.3 on 2018-12-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(default='', upload_to='Logo'),
            preserve_default=False,
        ),
    ]
