# Generated by Django 2.1.3 on 2018-12-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0003_auto_20181228_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='correo',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
