# Generated by Django 2.1.3 on 2019-01-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0004_empresa_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='numero_de_cuenta',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
