# Generated by Django 2.1.3 on 2019-01-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0005_empresa_numero_de_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='link_encuesta',
            field=models.URLField(blank=True, null=True),
        ),
    ]
