# Generated by Django 2.1.3 on 2019-01-29 20:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0006_empresa_link_encuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='giro_de_la_empresa',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='historia',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='mision',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='valores',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='vision',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
