# Generated by Django 2.1.3 on 2019-02-13 01:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0010_secciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuienesSomos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('texto', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
