# Generated by Django 2.1.3 on 2019-02-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0011_quienessomos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='historia',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='mision',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='que_es',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='valores',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='vision',
        ),
        migrations.AddField(
            model_name='empresa',
            name='titulo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='giro_de_la_empresa',
            field=models.TextField(blank=True, null=True),
        ),
    ]
