# Generated by Django 2.1.3 on 2019-02-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0012_auto_20190213_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='correopaypal',
            field=models.CharField(default='correopaypal@gmail.com', max_length=100),
            preserve_default=False,
        ),
    ]
