# Generated by Django 2.1.3 on 2019-02-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0014_auto_20190218_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='banco',
            field=models.CharField(default='Banamex', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo_tarjeta',
            field=models.CharField(blank=True, choices=[('Débito', 'Débito'), ('Crédito', 'Crédito')], max_length=50, null=True),
        ),
    ]
