# Generated by Django 2.1.3 on 2019-02-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0015_auto_20190226_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='tipo_tarjeta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
