# Generated by Django 2.1.3 on 2019-08-03 00:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0016_auto_20190226_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='politicas',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='terminos_condiciones',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
