# Generated by Django 2.1.3 on 2019-08-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0018_auto_20190802_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='fav_logo',
            field=models.ImageField(blank=True, null=True, upload_to='Logo'),
        ),
    ]
